// Copyright (c) 2023 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//   IBM Corporation
:projectid: microprofile-config-profile
:page-layout: guide-multipane
:page-duration: 20 minutes
:page-releasedate: 2023-01-31
:page-description: Learn how to use the config profile feature in MicroProfile Config to provide configurations for different phases in the DevOps lifecycle.
:page-tags: ['MicroProfile']
:page-permalink: /guides/{projectid}
:page-related-guides: ['microprofile-config-intro', 'microprofile-config-apis']
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/prod
:source-highlighter: prettify
:page-seo-title: Configuring Java microservices for multiple environments using Eclipse MicroProfile Config
:page-seo-description: A tutorial and example on how to configure multiple project environments and development stages in DevOps lifecycle for Java microservices using the config profile feature in Eclipse MicroProfile Config.
:guide-author: Open Liberty
= Configuring microservices for multiple environments

[.hidden]
NOTE: This repository contains the guide documentation source. To view the guide in published form, view it on the https://openliberty.io/guides/{projectid}.html[Open Liberty website].

Learn how to configure microservices for multiple environments using MicroProfile Config's config profile feature, allowing for streamlined management of configurations across different phases of the DevOps lifecycle.

:win: WINDOWS
:mac: MAC
:linux: LINUX

// =================================================================================================
// What you'll learn
// =================================================================================================
== What you'll learn

Managing configurations for microservices can be a time-consuming task, especially when configuration properties need to be adjusted for different stages of the DevOps lifecycle. MicroProfile Config's https://download.eclipse.org/microprofile/microprofile-config-3.0/microprofile-config-spec-3.0.html#configprofile[config profile^] feature offers an efficient solution by allowing you to easily manage configurations for your microservices in various environments, from development to production and across your DevOps pipeline. By providing different sets of configuration properties for each environment, you can streamline the process and focus on delivering your application with ease.

You'll learn how to provide different sets of configuration properties for each environment using the MicroProfile Config's config profile feature for your microservices.

This guide builds on the basics of the https://openliberty.io/guides/microprofile-config-intro.html[Separating configuration from code in microservices^] guide and the https://openliberty.io/guides/microprofile-config.html[Configuring microservices^] guide. If you are not familiar with externalizing the configuration of microservices, it will be helpful to read https://openliberty.io/docs/latest/external-configuration.html[this document^] and complete those guides before proceeding.

The application that you will be working with is a `query` service, which fetches information about the running JVM from a `system` microservice. The `system` microservice requires different ports and credentials to access in the testing environment compared to the development environment. To address this, you'll use MicroProfile Config's config profile feature to provide the `query` service with different configurations for accessing the `system` service in each environment.

// =================================================================================================
// Getting Started
// =================================================================================================

[role=command]
include::{common-includes}/gitclone.adoc[]

// =================================================================================================
== Running the application in the testing environment

Navigate to the `start` directory to begin.

The starting Java project, which you can find in the `start` directory, is a multi-module Maven project that's made up of the `system` and `query` microservices. Each microservice resides in its own corresponding directory, `system` and `query`. 

The `system` microservice contains the three build profiles: `testing`, `development` and `production`. To start the `system` service in `testing` environment, run the following commands to navigate to the `system` directory and deploy the `system` service to Open Liberty:

[role='command']
```
cd system
mvn -P testing liberty:run
```

// file 0
system/pom.xml
[source, XML, linenums, role='code_column']
----
include::finish/system/pom.xml[]
----

// file 1
system/server.xml
[source, XML, linenums, role='code_column']
----
include::finish/system/src/main/liberty/config/server.xml[]
----

During testing, the server configurations from the [hotspot=testing file=0]`testing` profile in the [hotspot file=0]`system/pom.xml` file are used for running the `system` service. You can find out that the `system` service runs on port [hotspot=test.port file=0]`9082` with context root [hotspot=test.context.root file=0]`system/test`, and a basic user registry is set up with username [hotspot=test.username file=0]`bob` and password [hotspot=test.password file=0]`bobpwd` to authorize access to resources from other services. Note that the `basicRegistry` element is a simple case for learning purposes, and for more information on different user registries, see the https://openliberty.io/docs/latest/user-registries-application-security.html[User registries documentation^].

Next, open another command-line session.

When you run Open Liberty in development mode, known as dev mode, the server listens for file changes and automatically recompiles and deploys your updates whenever you save a new change. Run the following commands to navigate to the `query` directory and start the `query` service in dev mode:

[role='command']
```
cd query
mvn liberty:dev
```

After you see the following message, your runtime in dev mode is ready:

[source, role="no_copy"]
----
**************************************************
*     Liberty is running in dev mode.
----

Dev mode holds your command-line session to listen for file changes. Open another command-line session to continue, or open the project in your editor.

// file 2
query/microprofile-config.properties
[source, Properties, linenums, role='code_column']
----
include::start/query/src/main/resources/META-INF/microprofile-config.properties[]
----

Navigate to the [hotspot=system file=2]`query/src/main/resources/META-INF/microprofile-config.properties` local configuration file to check some static configuration. This file is the default configuration source for an application using MicroProfile Config and contains the required properties to access the `testing` environment of the `system` service.

Point your browser to the http://localhost:9085/query/systems/localhost URL. You can see the current OS and Java version in JSON format. The URL retrieves the system property information for the `localhost` hostname by making a request to the `system` service at `\http://localhost:<system.httpPort>/<system.contextRoot>/property/{property}`.

After you finish checking out the application, stop the `system` service by pressing `CTRL+C` in the command-line session where you started the `system` service. Alternatively, you can run the `liberty:stop` goal from the `system` directory in another shell session:

[role='command']
```
mvn liberty:stop
```

// =================================================================================================
== Switching to the development environment

// file 0
system/pom.xml
[source, XML, linenums, role='code_column']
----
include::finish/system/pom.xml[]
----

Restart the `system` service in [hotspot=development file=0]`development` environment by running the following Maven goal from the `system` directory:

[role='command']
```
mvn liberty:dev
```

After you see the following message, your runtime in dev mode is ready:

[source, role="no_copy"]
----
**************************************************
*     Liberty is running in dev mode.
----

During development, the server configurations from the [hotspot=development file=0]`development` profile in the [hotspot file=0]`system/pom.xml` file are used for running the `system` service. The `system` service now runs on port [hotspot=port file=0]`9081` with context root [hotspot=context.root file=0]`system/dev`, and the credentials for the user registry are updated with username [hotspot=username file=0]`alice` and password [hotspot=password file=0]`alicepwd` for authentication to the service. 

// file 1
query/microprofile-config.properties
[source, Properties, linenums, role='code_column']
----
include::start/query/src/main/resources/META-INF/microprofile-config.properties[]
----

Test the connection between the `query` service and the `system` service by pointing your browser to the http://localhost:9085/query/systems/localhost URL. The `query` service returns the message: `{"fail":"Failed to reach the client localhost."}`.

This failure occurs because the `system` service was started with the `development` profile, while the configuration properties defined in the [hotspot=system file=1]`query/src/main/resources/META-INF/microprofile-config.properties` file are set for the `testing` environment. 

To resolve the issue, you'll create a configuration profile in the `query` service with the configuration properties necessary to access the `system` service in the `development` environment.

// =================================================================================================
== Creating the configuration profile at the property level

MicroProfile Config's config profile feature allows for the supply of configurations for different environments, such as development, testing, and production, while only a single profile is active. The active profile is set using the `mp.config.profile` property, which can be set in any of the ConfigSources or at application startup. Once set, the corresponding configuration properties associated with the active profile are used. 

Creating configuration profiles at the property level is useful when only a few configuration properties need to be set differently for each DevOps stage, such as when you require different database connection settings in different environments. 

To provide a configuration property for a particular config profile, use the `%<mp.config.profile>.<property name> = <value>` syntax.

In this example, you will provide configuration properties for the `development` environment to the `query` service at the property level.

[role="code_command hotspot file=0", subs="quotes"]
----
#Replace the `microprofile-config.properties` file.#
`query/src/main/resources/META-INF/microprofile-config.properties`
----

// file 0
query/microprofile-config.properties
[source, properties, linenums, role="code_column"]
----
include::staging/query/src/main/resources/META-INF/microprofile-config.properties[]
----

// file 1
system/pom.xml
[source, XML, linenums, role='code_column']
----
include::finish/system/pom.xml[]
----

Configure the [hotspot=development file=0]`%development.*` properties in the `microprofile-config.properties` file based on the values from the [hotspot=developmentProperties file=1]`development` profile of the `system` service.

Once you have updated the properties, stop the `query` service by pressing `CTRL+C` in the command-line session where you ran the `query` service, or by typing `q` and then pressing the `enter/return` key.

After stopping the `query` service, restart it with the `development` config profile. To do so, run the following Maven goal from the `query` directory:

[role='command']
```
mvn liberty:dev -Dliberty.var.mp.config.profile="development"
```

By setting `mp.config.profile` to `development` as a Liberty variable, each `%development.*` property will override the value of its original property. For example, the [hotspot=dev.port file=0]`%development.system.httpPort` property will override the [hotspot=port file=0]`system.httpPort` property and the value will be resolved to `9081` in this case.

Keep in mind that the `mp.config.profile` property can be set in any of the ConfigSources, but it is read only at application startup. Any changes made after that will be ignored until the next application startup.

After restarting the `query` service with the `development` config profile, you can now access the application by using the http://localhost:9085/query/systems/localhost URL. You can see the current OS and Java version in JSON format.

// =================================================================================================
== Creating the configuration profile using ConfigSource

In addition to creating configuration profiles at the property level, it's also possible to create configuration profiles using ConfigSources. This can be particularly useful when you need to manage a large number of configuration properties for different environments. For instance, each DevOps stage may require the application to run on different ports and context roots. Using ConfigSource to externalize and customize these configurations leads to a cleaner and more modular code design.

To create a configuration profile at the Config Source level, simply create a file under the `META-INF` folder on the classpath with the naming convention `microprofile-config-<mp.config.profile>.properties`. Once you have created the file, you can add your configuration properties to it with the `<property name>=<value>` syntax. 

In this example, you will provide configuration properties for the `development` environment to the `query` service using ConfigSource.

// file 0
[role="code_command hotspot file=0", subs="quotes"]
----
#Create the `microprofile-config-development.properties` file.#
`query/src/main/resources/META-INF/microprofile-config-development.properties`
----

query/microprofile-config-development.properties
[source, properties, linenums, role="code_column hide_tags=userPassword,properties,contactEmail,roleAndQuery"]
----
include::finish/query/src/main/resources/META-INF/microprofile-config-development.properties[]
----

// file 1
system/pom.xml
[source, XML, linenums, role='code_column']
----
include::finish/system/pom.xml[]
----

Define the [hotspot=system file=0]`system.*` properties in the `microprofile-config-development.properties` file based on the values from the [hotspot=developmentProperties file=1]`development` profile of the `system` service.

To use these configuration properties, 

// file 2
[role="code_command hotspot file=2", subs="quotes"]
----
#Replace the `microprofile-config.properties` file.#
`query/src/main/resources/META-INF/microprofile-config.properties`
----

query/microprofile-config.properties
[source, properties, linenums, role="code_column hide_tags=development"]
----
include::finish/query/src/main/resources/META-INF/microprofile-config.properties[]
----

// file 3
system/server.xml
[source, XML, linenums, role='code_column']
----
include::finish/system/src/main/liberty/config/server.xml[]
----

Update the `microprofile-config.properties` file by removing the `%development.\*` properties and setting the `system.*` properties to their default production values from the [hotspot=defaultConfig file=3]`system/server.xml` file.

Since the active profile is set to `development`, the [hotspot file=0]`microprofile-config-development.properties` file is loaded on top of the default `microprofile-config.properties` file. Therefore, any [hotspot=system file=0]`system.*` properties specified in the former take precedence over the values in the latter.

Because you are running the `query` service in dev mode, the changes that you made were automatically picked up. Point your browser to the http://localhost:9085/query/systems/localhost URL to check out the application again. You see the current OS and Java version in JSON format.

// ===========================================================================================
== Implementing test cases

You will create endpoint tests to test the basic functionality of the `query` microservice. If a test failure occurs, then you might have introduced a bug into the code.

// file 0
[role="code_command hotspot file=0", subs="quotes"]
----
#Create the `QueryEndpointIT` class.#
`query/src/test/java/it/io/openliberty/guides/query/QueryEndpointIT.java`
----

QueryEndpointIT.java
[source, java, linenums, role="code_column hide_tags=copyright"]
----
include::finish/query/src/test/java/it/io/openliberty/guides/query/QueryEndpointIT.java[]
----

// file 1
query/pom.xml
[source, XML, linenums, role='code_column']
----
include::finish/query/pom.xml[]
----

See the following descriptions of the test cases:

* [hotspot=testQuerySystem file=0]`testQuerySystem()` verifies the `/query/systems/{hostname}` endpoint.

* [hotspot=testUnknownHost file=0]`testUnknownHost()` verifies that an unknown host or a host that does not expose their JVM system properties is correctly handled with a fail message.

**Running the tests**

Because you started Open Liberty in dev mode, you can run the tests by pressing the enter/return key from the command-line session where you started the `query` service. If the tests pass, you see output similar to the following example:

[source, role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.query.QueryEndpointIT
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.703 s - in it.io.openliberty.guides.query.QueryEndpointIT

Results:

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
----

When you are done checking out the application in `development` environment, exit dev mode by pressing `CTRL+C` in the command-line sessions where you ran the `system` and `query` services, or by typing `q` and then pressing the `enter/return` key. 

// ===========================================================================================
== Testing the application

You will implement several endpoint tests to test the basic functionality of the `query` microservice. If a test failure occurs, then you might have introduced a bug into the code.

// file 0
[role="code_command hotspot file=0", subs="quotes"]
----
#Create the `QueryEndpointIT` class.#
`query/src/test/java/it/io/openliberty/guides/query/QueryEndpointIT.java`
----

QueryEndpointIT.java
[source, java, linenums, role="code_column hide_tags=copyright"]
----
include::finish/query/src/test/java/it/io/openliberty/guides/query/QueryEndpointIT.java[]
----

// file 1
query/pom.xml
[source, XML, linenums, role='code_column']
----
include::finish/query/pom.xml[]
----

See the following descriptions of the test cases:

* [hotspot=testQuerySystem file=0]`testQuerySystem()` verifies the `/query/systems/{hostname}` endpoint.

* [hotspot=testUnknownHost file=0]`testUnknownHost()` verifies that an unknown host or a host that does not expose their JVM system properties is correctly handled with a fail message.

=== Running the tests

First, test the application under the `development` environment.

Because you started Open Liberty in dev mode, you can run the tests by pressing the enter/return key from the command-line session where you started the `query` service. If the tests pass, you see output similar to the following example:

[source, role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.query.QueryEndpointIT
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.703 s - in it.io.openliberty.guides.query.QueryEndpointIT

Results:

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0
----

When you are done checking out the application in `development` environment, exit dev mode by pressing `CTRL+C` in the command-line sessions where you ran the `system` and `query` services, or by typing `q` and then pressing the `enter/return` key. 

// file 0
scripts/testApp.sh|.bat
[source, XML, linenums, role='code_column']
----
include::finish/scripts/testApp.sh[]
----

Now, navigate to the `start` directory. 

Test the application under the `testing` environment by running the following script that contains different Maven goals to [hotspot=build file=0]`build`, [hotspot=start file=0]`start`, [hotspot=test file=0]`test`, and [hotspot=stop file=0]`stop` the services:

include::{common-includes}/os-tabs.adoc[]

[.tab_content.mac_section.linux_section]
--
[role='command']
```
./scripts/testApp.sh
```
--

[.tab_content.windows_section]
--
[role='command']
```
scripts\testApp.bat
```
--


If the tests pass, you see output similar to the following example:

[source, role="no_copy"]
----
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.system.SystemEndpointIT
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.539 s - in it.io.openliberty.guides.system.SystemEndpointIT

Results:

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0

...

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.io.openliberty.guides.query.QueryEndpointIT
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.706 s - in it.io.openliberty.guides.query.QueryEndpointIT

Results:

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0

----


== Great work! You're done!

You learned how to use the config profile feature in MicroProfile Config to configure the application for multiple environments.

Feel free to try one of the related guides. They demonstrate new technologies that you can learn to expand on what you built in this guide.

include::{common-includes}/attribution.adoc[subs="attributes"]
